feat: copy overview page from dataset-catalog-gui
Informasjonsforvaltning/registration-portal pull request #1
Opened 2022-01-25 13:32 UTC by NilsOveTen

2022-01-27 10:33 UTC, valosnah requested changes

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-demo.yaml
> +    - uses: actions/checkout@v2
Du kan fjerne actions/checkout i demo-workflowen

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-demo.yaml
> +      uses: google-github-actions/setup-gcloud@master
```
- name: Setup gcloud CLI for deploy      
  uses: google-github-actions/auth@v0
  with:
    credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
```

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +    - uses: actions/checkout@v2
```
- name: Checkout
  uses: actions/checkout@v2
```

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +    - name: Setup gcloud CLI for image-store
```
- name: Setup gcloud CLI for image-store      
  uses: google-github-actions/auth@v0
  with:
    credentials_json: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
```

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +      uses: actions/cache@v2.1.6
/cache@2

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +      uses: docker/setup-buildx-action@v1.6.0
`@1`

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-prod.yaml
> +    - name: Setup gcloud CLI for deploy
```
- name: Setup gcloud CLI for deploy     
  uses: google-github-actions/auth@v0
  with:
    credentials_json: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
```

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +    - uses: actions/checkout@v2
```
- name: Checkout
  uses: actions/checkout@v2
```

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +    - name: Setup gcloud CLI for image-store
```
- name: Setup gcloud CLI for image-store      
  uses: google-github-actions/auth@v0
  with:
    credentials_json: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
```

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +      uses: actions/cache@v2.1.6
`@2`

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +      uses: docker/setup-buildx-action@v1.6.0
`@1`

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +    - name: Setup gcloud CLI for deploy
```
- name: Setup gcloud CLI for deploy      
  uses: google-github-actions/auth@v0
  with:
    credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
```

2022-01-27 10:33 UTC, valosnah commented on .github/workflows/run-tests.yaml
> +      - uses: actions/checkout@v2
```
- name: Checkout
  uses: actions/checkout@v2
```

2022-01-27 10:33 UTC, valosnah commented on config.template.js
> +  CONCEPT_REGISTRATION_API_HOST: '$CONCEPT_REGISTRATION_API_HOST',
Vurdere å peke denne til den nye api-url'en?
concept-catalog.fellesdatakatalog.digdir.no ?
CONCEPT_CATALOG_BASE_URI

Vet ikke om denne eller noe annet er avhengig av at denne env var'en peker til den gamle url'en (registrering-begrep-api.fellesdatakatalog.digdir.no)

2022-01-27 10:33 UTC, valosnah commented on docker-compose.yml
> +      - CONCEPT_REGISTRATION_API_HOST=https://registrering-begrep-api.fellesdatakatalog.digdir.no
Huske å endre denne hvis du er enig i kommentaren i config.template.js

2022-01-27 10:33 UTC, valosnah commented on src/components/catalog/index.tsx
> +import { getConceptCount } from '../../services/api/concept-registration-api/host';
Hvis vi endrer concept-url'en burde kanskje denne pathen endres til /concept-catalog/host

2022-01-27 10:33 UTC, valosnah commented on src/components/catalog/index.tsx
> +import { getDatasetsCount } from '../../services/api/registration-api/host';
Denne burde kanskje omdøpes til dataset-catalog/host ?

2022-01-27 10:33 UTC, valosnah commented on src/env.ts
> +    CONCEPT_REGISTRATION_API_HOST:
Se kommentar i config.template

2022-01-27 14:05 UTC, NilsOveTen commented on .github/workflows/deploy-demo.yaml
> +    - uses: actions/checkout@v2
318169d

2022-01-27 14:05 UTC, NilsOveTen commented on .github/workflows/deploy-demo.yaml
> +      uses: google-github-actions/setup-gcloud@master
318169d

2022-01-27 14:05 UTC, NilsOveTen commented on .github/workflows/deploy-prod.yaml
> +    - uses: actions/checkout@v2
318169d

2022-01-27 14:05 UTC, NilsOveTen commented on .github/workflows/deploy-prod.yaml
> +    - name: Setup gcloud CLI for image-store
318169d

2022-01-27 14:05 UTC, NilsOveTen commented on .github/workflows/deploy-prod.yaml
> +      uses: actions/cache@v2.1.6
318169d

2022-01-27 14:05 UTC, NilsOveTen commented on .github/workflows/deploy-prod.yaml
> +    - name: Setup gcloud CLI for deploy
318169d

2022-01-27 14:05 UTC, NilsOveTen commented on .github/workflows/deploy-staging.yaml
> +    - uses: actions/checkout@v2
318169d

2022-01-27 14:06 UTC, NilsOveTen commented on .github/workflows/deploy-staging.yaml
> +    - name: Setup gcloud CLI for image-store
318169d

2022-01-27 14:06 UTC, NilsOveTen commented on .github/workflows/deploy-staging.yaml
> +      uses: actions/cache@v2.1.6
318169d

2022-01-27 14:06 UTC, NilsOveTen commented on .github/workflows/deploy-staging.yaml
> +      uses: docker/setup-buildx-action@v1.6.0
318169d

2022-01-27 14:06 UTC, NilsOveTen commented on .github/workflows/deploy-staging.yaml
> +    - name: Setup gcloud CLI for deploy
318169d

2022-01-27 14:06 UTC, NilsOveTen commented on .github/workflows/run-tests.yaml
> +      - uses: actions/checkout@v2
318169d

2022-01-27 14:07 UTC, NilsOveTen commented on src/env.ts
> +    CONCEPT_REGISTRATION_API_HOST:
b678752

2022-01-27 14:07 UTC, NilsOveTen commented on src/components/catalog/index.tsx
> +import { getDatasetsCount } from '../../services/api/registration-api/host';
b678752

2022-01-27 14:07 UTC, NilsOveTen commented on src/components/catalog/index.tsx
> +import { getConceptCount } from '../../services/api/concept-registration-api/host';
b678752

2022-01-27 14:07 UTC, NilsOveTen commented on docker-compose.yml
> +      - CONCEPT_REGISTRATION_API_HOST=https://registrering-begrep-api.fellesdatakatalog.digdir.no
b678752

2022-01-27 14:07 UTC, NilsOveTen commented on config.template.js
> +  CONCEPT_REGISTRATION_API_HOST: '$CONCEPT_REGISTRATION_API_HOST',
b678752

2022-01-27 14:25 UTC, valosnah approved these changes

2022-01-27 14:48 UTC, oyvindis commented on package.json
> +  "dependencies": {
Det blir vel med en god del pakker her som egentlig ikke vil være i bruk? Bl.a. "designsystemet" er noe vi ikke vil bruke lenger så en ny applikasjon burde ikke bruke den lenger.

2022-01-27 15:03 UTC, NilsOveTen commented
> Usikker på hva du vil ha review på, alt er kopi fra før?
> 
> Så enten skal alt bare kopieres "as is" eller skal vi gjøre endringer samtidig? Det er jo f.eks. en del avhengigheter vi ikke burde ha med videre, kommenterte f.eks. på designsystemet.

Mest en dobbeltsjekk på at jeg ikke kopierer inn mer enn nødvendig

2022-01-27 15:15 UTC, NilsOveTen commented on package.json
> +  "dependencies": {
Det blir importert i noen scss-filer og her: src/entrypoints/main/styles/index.ts, dunno hvilken effekt det vil ha om jeg bare fjerner de importene. Skal jeg prøve?

2022-01-28 10:02 UTC, oyvindis commented on src/assets/style/react-tags-override.scss
> +@import '../../../node_modules/designsystemet/fdk-designsystem-bootstrap4/scss/colors.scss';
Tror hele denne ikke vil være i bruk her.

2022-01-28 10:08 UTC, oyvindis approved these changes
Ser ikke noe overflødig her så kan merge som det er.

2022-01-31 08:21 UTC, NilsOveTen commented on src/assets/style/react-tags-override.scss
> +@import '../../../node_modules/designsystemet/fdk-designsystem-bootstrap4/scss/colors.scss';
react-tags blir strengt tatt ikke brukt, så fjerna hele fila: 08556d5

2022-01-31 08:37 UTC, merged