fix: change uri for registrere data link internal header
Informasjonsforvaltning/registration-portal pull request #149
Opened 2023-04-12 13:10 UTC by hegeaal

closes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/194

2023-04-12 13:26 UTC, jeffreiffers requested changes

2023-04-12 13:26 UTC, jeffreiffers commented on src/components/header/index.tsx
> +      <Link href={`${FDK_REGISTRATION_BASE_URI}`}>Registrere data</Link>
```suggestion
      <Link href={FDK_REGISTRATION_BASE_URI}>Registrere data</Link>
```

2023-04-14 06:24 UTC, NilsOveTen approved these changes

2023-04-14 08:06 UTC, pooriamehregan approved these changes

2023-04-14 09:09 UTC, jeffreiffers approved these changes

2023-04-14 09:13 UTC, merged